[package]
name = "dreamtime-server"
version = "0.1.0"
authors = ["Kirill Lastovirya <kirill.lastovirya@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
diesel = { version = "1.4.6", features = ["postgres"] }
dotenv = "0.15.0"

[lib]
name = "dreamland_library"
path = "src/lib.rs"

[[bin]]
name = "read_users"
path = "src/read_users.rs"

[[bin]]
name = "write_users"
path = "src/write_users.rs"