[package]
name = "dreamtime-server"
version = "0.1.0"
authors = ["Kirill Lastovirya <kirill.lastovirya@gmail.com>"]
edition = "2018"

[lib]
name = "dreamtime_library"
path = "src/lib.rs"

[[bin]]
name = "read_users"
path = "src/read_users.rs"

[[bin]]
name = "write_users"
path = "src/write_users.rs"

[[bin]]
name = "run_server"
path = "src/run_server.rs"

[dependencies]
diesel = { version = "1.4.6", features = ["postgres"] }
dotenv = "0.15.0"
rocket = { git = "https://github.com/SergioBenitez/Rocket", branch = "master" }
rocket_contrib = { git = "https://github.com/SergioBenitez/Rocket", branch = "master" }
