@baseUrl = http://localhost:8000/api/v1
@apiKey = kirill@ch

### 
# Health check
@name = health
GET {{baseUrl}}/
X-Api-Key: {{apiKey}}

### 
# Initiate a new user session
# Will either create a new user or pick up an existent one 
@name = connect_user
POST {{baseUrl}}/users/connect
X-Api-Key: {{apiKey}}
Content-Type: application/json

{
    "name": "Kirill",
    "email": "kirill@example.com",
    "password": "bobo"
}

### 
# Get list of users
# later will limit by radius
@name = get_all_users
GET {{baseUrl}}/users
X-Api-Key: {{apiKey}}


